apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphjin.fullname" . }}-jwt-public-key
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
data: 
  publicKey: {{ .Values.jwt.publicKey | quote }}