apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "graphjin.fullname" . }}-config
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
data: 
  config: {{ .Values.config | toYaml | quote | b64enc }}
