apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphjin.fullname" . }}
  labels:
    {{- include "graphjin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "graphjin.selectorLabels" . | nindent 4 }}
